### ISSUE TITLE
How to make each iteration add more details 

### ISSUE THREAD

**Issue by frankyifei** [blepping/comfyui_jankdiffusehigh#3]
with normal hi-res fix, we can control how much detail we want to improve by setting denoise value, how to do it with this new method?

**Comment by blepping** [comment]
you can (and should) still use a denoise with the `highres_sigmas` you pass to the node. it will work the same as normal if you're familiar with `SamplerCustom`.

if you're asking how to use a different denoise for each iteration, that's possible too but you'll need to do it via the YAML parameters feature. it's _reasonably_ well documented in the README (you need to expand the section to see it since it's fairly big) and has a few examples but i'll show you a few specifically for that as well. i would recommend reading that section in the README though.

first, you can just define a schedule via YAML parameters rather than passing in `highres_sigmas` at all:

```yaml
schedule_override:
    schedule_name: karras
    steps: 20
    denoise: 0.3
```

it's also possible to override either the `schedule_override` defined at the base-level (or the `highres_sigmas` you pass in) via iteration overrides which allow overriding nearly all parameters per iteration. for example, suppose you have 3 iterations and you want to do 0.3 denoise for the first, 0.2 for the second and 0.1 for the third, it would look like this:

```yaml
iteration_override:
    0:
      schedule_override:
          schedule_name: karras
          steps: 20
          denoise: 0.3
    1:
      schedule_override:
          schedule_name: karras
          steps: 20
          denoise: 0.2
    2:
      schedule_override:
          schedule_name: karras
          steps: 20
          denoise: 0.1
```

there are various ways to do it - you could do a schedule_override at the top level and then only override iterations 1 and 2 (they are indexed starting from 0). if you wanted to you could also change other parameters like `guidance_mode`, `guidance_steps` and so on - pretty much the only things you can't change are inputs like the VAE or upscale model (but you can control whether it gets used) and the number of iterations.

by the way, the `yaml_parameters` input in the node can be converted to a multi-line text widget or you can connect a different multiline text node to it, whichever you prefer.

![image](https://github.com/user-attachments/assets/44d0e1cf-17a9-4dea-96a4-ffa1bb48c894)
